# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloRN
  
#  react_native_path = "./ReactnNative/node_modules/react-native”  #在podfile所在的目录下找到node_modules文件夹
#  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
#  pod "React", :path => react_native_path, :subspecs => [
#  'Core',
#  'RCTActionSheet',
#  'RCTGeolocation',
#  'RCTImage',
#  'RCTLinkingIOS',
#  'RCTNetwork',
#  'RCTSettings',
#  'RCTText',
#  'RCTVibration',
#  'RCTWebSocket',
#  ]

    # 'node_modules'目录一般位于根目录中
    # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket', # 这个模块是用于调试功能的
        # 在这里继续添加你所需要的模块
    ]
    # 如果你的RN版本 >= 0.42.0，则加入下面这行
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"



#  pod 'React'
#  pod 'React/Core'
#  pod 'React/ART'
#  pod 'React/RCTActionSheet'
#  pod 'React/RCTAdSupport'
#  pod 'React/RCTGeolocation'
#  pod 'React/RCTImage'
#  pod 'React/RCTNetwork'
#  pod 'React/RCTPushNotification'
#  pod 'React/RCTSettings'
#  pod 'React/RCTText'
#  pod 'React/RCTVibration'
#  pod 'React/RCTWebSocket'
#  pod 'React/RCTLinkingIOS'
#
#  pod 'Yoga'


  target 'HelloRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloRNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
